### ISSUE TITLE
'DPN' object has no attribute 'input_space'  Cifar10 example

### ISSUE THREAD

**Issue by morawi** [creafz/pytorch-cnn-finetune#3]
When setting the pre_trained_model to False, running 'dpns' gave the error _'DPN' object has no attribute 'input_space'_  in Cifar10 example. Except Resntes, all models gave this error. Using the attribute input_size=(32, 32)  in make_model resolved the issue. [32x32] is the cifar10 resolution for each band.
```
model = make_model(
    args.model_name,
    pretrained=True,
    num_classes=len(classes),
    dropout_p=args.dropout_p,
    input_size=(32, 32) 
)
```
However, this 'input_size' gave the error: _ResNet' object has no attribute 'features'_
for all the Resnets. Thus, an if statement may be used to make-the-model.
NB. For VGG* and squeezenet*, we need to provide the input-size in any case, _Exception: You must provide input_size, e.g. make_model(vgg11, num_classes=10, pretrained=True, input_size=(224, 224)_

**Comment by creafz** [comment]
First exception (`'DPN' object has no attribute 'input_space'`) should be fixed in 
b690d27. The exception occurred because only pre-trained models contain attributes such as `input_space` or `input_shape`, but the library tried to read those attributes even when `pretrained` was set to `False`.

**Comment by creafz** [comment]
The second exception should be fixed in e7dc01f. I have changed the function that calculates the number of input features for the classifier, now it should work correctly for all models.

**Comment by morawi** [comment]
I think there is still an issue with the code, 
File "/anaconda3/lib/python3.6/site-packages/cnn_finetune/base.py", line 160, in calculate_classifier_in_features
    with no_grad_variable(torch.zeros(1, 3, *self.input_size)) as input_var:

TypeError: zeros() argument after * must be an iterable, not NoneType

**Comment by creafz** [comment]
Can you give an example of code that produces this exception?

Calls to `make_model` like `model = make_model('dpn68', pretrained=False, num_classes=10, dropout_p=0.5, input_size=(32, 32))` and `model = make_model('dpn68', pretrained=False, num_classes=10, dropout_p=0.5)` work for me without any errors.

**Comment by morawi** [comment]
Strangely, it is working now without problems.
